export const mockData = {
  categories: [
    { id: "1", name: "Thép xây dựng", icon: "🔩", count: 4820, hot: true },
    { id: "2", name: "Thép hình I/H/U", icon: "⚙️", count: 2140 },
    { id: "3", name: "Thép hộp / ống", icon: "📦", count: 1960 },
    { id: "4", name: "Sắt tấm / thép lá", icon: "🟫", count: 1340 },
    { id: "5", name: "Thép lưới / hàng rào", icon: "🔗", count: 880 },
    { id: "6", name: "Inox / Không gỉ", icon: "✨", count: 1200 },
    { id: "7", name: "Sắt tấm / thép lá", icon: "🟫", count: 1340 },
    { id: "8", name: "Thép lưới / hàng rào", icon: "🔗", count: 880 },
    { id: "9", name: "Inox / Không gỉ", icon: "✨", count: 1200 },
  ],

  products: [
    {
      id: "p1",
      seller: "Thép Hòa Phát HN",
      sellerInitial: "H",
      sellerColor: "#dc2626",
      verified: true,
      badge: "HOT",
      name: "Thép cây CB300V D16 — Cuộn 1.2 tấn",
      tags: ["D16mm", "CB300V", "Hòa Phát"],
      price: 17200,
      originalPrice: 17600,
      unit: "kg",
      views: 1240,
      location: "Hà Nội",
      icon: "🔩",
    },
    {
      id: "p2",
      seller: "Vina Steel HCM",
      sellerInitial: "V",
      sellerColor: "#7c3aed",
      verified: true,
      badge: "MỚI",
      name: "Thép hình I100×50×5 — TCVN 7571",
      tags: ["I100×50", "TCVN", "TP.HCM"],
      price: 19500,
      unit: "kg",
      views: 856,
      location: "TP.HCM",
      icon: "⚙️",
    },
    {
      id: "p3",
      seller: "Thép Trường Thành",
      sellerInitial: "T",
      sellerColor: "#16a34a",
      verified: true,
      badge: "MỚI",
      discount: 5,
      name: "Thép hộp 40×40×2 — Mạ kẽm nhúng nóng",
      tags: ["40×40×2", "Mạ kẽm"],
      price: 22800,
      originalPrice: 24000,
      unit: "kg",
      views: 2100,
      location: "Bình Dương",
      icon: "📦",
    },
    {
      id: "p4",
      seller: "An Phát Inox",
      sellerInitial: "A",
      sellerColor: "#0284c7",
      verified: true,
      badge: "VIP",
      name: "Inox 304 tấm cán nguội 1.2×1220mm",
      tags: ["SS304", "1.2mm", "2B"],
      price: 68000,
      unit: "kg",
      views: 640,
      location: "Đà Nẵng",
      icon: "✨",
    },
    {
      id: "p5",
      seller: "Pomina Steel",
      sellerInitial: "P",
      sellerColor: "#b45309",
      verified: true,
      name: "Thép cây D14 CB400V — Thanh 11.7m",
      tags: ["D14", "CB400V", "Pomina"],
      price: 18400,
      unit: "kg",
      views: 920,
      location: "TP.HCM",
      icon: "🔩",
    },
    {
      id: "p6",
      seller: "Minh Trung Steel",
      sellerInitial: "M",
      sellerColor: "#0f766e",
      verified: true,
      badge: "HOT",
      name: "Thép tấm CT3 dày 6mm — 1500×6000",
      tags: ["CT3", "6mm", "Hà Nội"],
      price: 21400,
      unit: "kg",
      views: 740,
      location: "Hà Nội",
      icon: "🟫",
    },
  ],

  totalListings: 18000,

  featuredBrand: {
    name: "HOÀ PHÁT",
    tagline: "Chính hãng · Nhà sản xuất",
    productName: "Thép cây CB300V D16 — Dung Quất · Giao ngay",
    price: 17200,
    unit: "kg",
    tags: ["D16 CB300V", "Còn hàng 500+ tấn", "Xuất VAT"],
  },

  sideBrand: {
    name: "Pomina Steel",
    initial: "P",
    tagline: "Đã xác minh",
    topSeller: true,
    priceList: [
      { label: "Thép cây D12 CB400V", price: 17800 },
      { label: "Thép cây D14 CB400V", price: 18400 },
      { label: "Thép cây D16 CB400V", price: 18200 },
    ],
    priceTable: [
      {
        label: "Thép cây D16",
        price: 17200,
        change: 1.2,
        changeDir: "up" as const,
      },
      {
        label: "Thép hộp 40×40",
        price: 22800,
        change: 0.4,
        changeDir: "down" as const,
      },
      { label: "Thép I100", price: 19500 },
    ],
  },
};
